### ISSUE TITLE
有时间的话能不能整些课件或者视频教学

### ISSUE THREAD

**Issue by xuandu** [ErosZy/md#3]
如何用wasm H5，从0到1开发无插件播放器

**Comment by xiaoxiangmoe** [comment]
建议不学音视频，找不到工作捏

**Comment by xuandu** [comment]
我就是做音视频的，工作确实不好找了，现在需求都是网路，协议，sdk组件，编解码都要会了

**Comment by xuandu** [comment]
> 建议不学音视频，找不到工作捏

我就是做音视频的，工作确实不好找了，现在需求都是网路，协议，sdk组件，视频渲染，gpu编解码，都要会了。好难呀

**Comment by ErosZy** [comment]
no plan.
